### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by Fcl1111** [chinhsuanwu/dreamfusionacc#7]
E:\ProgramData\tinycudann\lib\site-packages\tinycudann-1.7-py3.10-win-amd64.egg\tinycudann\modules.py:57: UserWarning: tinycudann was built for lower compute capability (86) than the system's (89). Performance may be suboptimal.
  warnings.warn(f"tinycudann was built for lower compute capability ({cc}) than the system's ({system_compute_capability}). Performance may be suboptimal.")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "E:\Download\Diffusion Model Review\文本3D生成\基于扩散模型的方法\dreamfusionacc\train.py", line 47, in <module>
    set_random_seed(config.seed)
  File "E:\Download\Diffusion Model Review\文本3D生成\基于扩散模型的方法\dreamfusionacc\utils.py", line 15, in set_random_seed
    torch.manual_seed(seed)
  File "E:\ProgramData\tinycudann\lib\site-packages\torch\random.py", line 40, in manual_seed
    torch.cuda.manual_seed_all(seed)
  File "E:\ProgramData\tinycudann\lib\site-packages\torch\cuda\random.py", line 113, in manual_seed_all
    _lazy_call(cb, seed_all=True)
  File "E:\ProgramData\tinycudann\lib\site-packages\torch\cuda\__init__.py", line 165, in _lazy_call
    callable()
  File "E:\ProgramData\tinycudann\lib\site-packages\torch\cuda\random.py", line 111, in cb
    default_generator.manual_seed(seed)
E:\ProgramData\tinycudann\lib\site-packages\torch\cuda\random.py:111: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_numpy.cpp:77.)
  default_generator.manual_seed(seed)
[INFO] loading stable diffusion...
Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]E:\ProgramData\tinycudann\lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\fcl\.cache\huggingface\hub\models--stabilityai--stable-diffusion-2-1-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Fetching 13 files: 100%|██████████| 13/13 [09:19<00:00, 43.03s/it]
Loading pipeline components...: 100%|██████████| 6/6 [00:08<00:00,  1.35s/it]
Traceback (most recent call last):
  File "E:\Download\Diffusion Model Review\文本3D生成\基于扩散模型的方法\dreamfusionacc\train.py", line 93, in <module>
    guidance = StableDiffusion(device=config.device, sd_version=config.sd_version)
  File "E:\Download\Diffusion Model Review\文本3D生成\基于扩散模型的方法\dreamfusionacc\guidance\stable_diffusion.py", line 90, in __init__
    self.scheduler = DDIMScheduler.from_pretrained(
  File "E:\ProgramData\tinycudann\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\ProgramData\tinycudann\lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 157, in from_pretrained
    return cls.from_config(config, return_unused_kwargs=return_unused_kwargs, **kwargs)
  File "E:\ProgramData\tinycudann\lib\site-packages\diffusers\configuration_utils.py", line 260, in from_config
    model = cls(**init_dict)
  File "E:\ProgramData\tinycudann\lib\site-packages\diffusers\configuration_utils.py", line 665, in inner_init
    init(self, *args, **init_kwargs)
  File "E:\ProgramData\tinycudann\lib\site-packages\diffusers\schedulers\scheduling_ddim.py", line 234, in __init__
    self.timesteps = torch.from_numpy(np.arange(0, num_train_timesteps)[::-1].copy().astype(np.int64))
RuntimeError: Numpy is not available

I would like to know the version number of numpy you are using.

**Comment by Fcl1111** [comment]
通过下载最新版本的numpy==1.x.x解决了
